### ISSUE TITLE
Take into account seeds

### ISSUE THREAD

**Issue by vdeb** [slidoapp/dbt-coverage#17]
It seems that seeds are not considered while reading manifest.json. As a result, the following error pops while running `dbt-coverage compute doc`

```sh
(venv_dbt) ➜  myCodeFolder git:(master) dbt-coverage compute doc                                
INFO:root:Loading catalog and manifest files from project dir: .
INFO:root:Successfully loaded 200 tables from catalog
Traceback (most recent call last):
  File "/Users/victor/myCodeFolder/venv_dbt/bin/dbt-coverage", line 8, in <module>
    sys.exit(app())
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/dbt_coverage/__init__.py", line 604, in compute
    do_compute(project_dir, cov_report, cov_type, cov_fail_under, cov_fail_compare)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/dbt_coverage/__init__.py", line 562, in do_compute
    catalog = load_files(project_dir)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/dbt_coverage/__init__.py", line 486, in load_files
    manifest = load_manifest(project_dir)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/dbt_coverage/__init__.py", line 477, in load_manifest
    manifest = Manifest.from_nodes(manifest_nodes)
  File "/Users/victor/myCodeFolder/venv_dbt/lib/python3.8/site-packages/dbt_coverage/__init__.py", line 121, in from_nodes
    table_name = id_to_table_name[table_id]
KeyError: 'seed.dbt_project.browsers'
```

Versions:
```
dbt-core==0.21.0
dbt-coverage==0.1.7
```
Python 3.8

**Comment by sweco** [comment]
Hey @vdeb, thanks for trying out the project and giving the feedback. I tried fixing the issue in version [0.1.8](https://github.com/slidoapp/dbt-coverage/releases/tag/v0.1.8) (also available on PyPI), please give it a try and let me know if it works for you!

**Comment by vdeb** [comment]
@sweco works well, thanks !
